// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "SickPlugin.h"

SickPlugin::SickPlugin()
{
}

SickPlugin::~SickPlugin()
{
}

QString SickPlugin::name()
{
    return "SickPlugin";
}

Q_EXPORT_PLUGIN2(SickPlugin, SickPlugin)
